### ISSUE TITLE
luci APP mosdns

### ISSUE THREAD

**Issue by ghost** [dogbutcat/openwrt-packages#1]
mos-chinadns has been revised to mosdns, and the results of the first generation of mosdns have been formed, can you develop luci for mosdns?

**Comment by dogbutcat** [comment]
Yeah, I've develop for days. At that time, mosdns didn't support socks5 forward, so the project used be shelved.

You know, it's near lunar year. I don't have much time to compile for testing, what worse is my home PC upgradation still under process.

One more thing, mosdns changed vary time during develop, I'm still paying attetion on it. So temporary for now, moschinadns is more stable option.

**Comment by ghost** [comment]
Maybe you are right, it needs more testing, right now.

**Comment by IrineSistiana** [comment]
@dogbutcat  Thanks for your attention on mosdns.

mosdns 的东西有点多，配置起来也很繁琐，因为原本是放在服务器上使用的。

如果路由用的话，也许可以精简。所以我在尝试做一个简化版 mosdns(暂时起名 mosdns-cn?)。 只用部分插件，就像 chinadns 一样，通过命令行给关键参数。其余配置和逻辑是固定的，只能屏蔽域名，屏蔽ipv6，分流。mosdns 更新的话也不会(或者很难)导致 mosdns-cn 不兼容。luci 配置也方便。

比如有这些参数:

- `-listen` 同时监听 tcp udp。
- `-remote-server` 可配置多次，指定多个服务器
- `-local-server` 可配置多次，指定多个服务器
- `-disable-ipv6 local|remote|all`  禁用谁的 ipv6

从外部导入的资源

- `-block-domain` 要屏蔽的域名
- `-remote-domain` 一定要分流的
- `-local-domain` 一定不要分流的
- `-local-IP` 本地 IP 范围

我不了解 openwrt 和 luci。欢迎建议或者来 mosdns 讨论。

**Comment by ghost** [comment]
@IrineSistiana 作为用户，我建议：
1）该mosdns是否已经可以稳定运行在openwrt x86/arm64上，尤其是在node切换时不会崩溃，前代产品mos-chinadns存在这个方面问题;
2）该mosdns是否已经支持socks5代理？
