### ISSUE TITLE
socks5 forward

### ISSUE THREAD

**Issue by ghost** [dogbutcat/openwrt-packages#2]
Hi,if I want to enable socks5 forwarding support, can I rewrite the configuration like this after enabling the socks5 server? What are the advantages compared to before?

> socks5: "127.0.0.1:1080"

**Comment by dogbutcat** [comment]
That's right, in `ip:port` format, no matter local or remote. I found if socks server not stable, mos-chinadns probably failed the forward until restart the application. I'm now using with openclash and feel fine.

**Comment by ghost** [comment]
That's a good idea.
