### ISSUE TITLE
mosdns已经更新v2.0.1版本，可以更新一下吗？

### ISSUE THREAD

**Issue by dudt** [dogbutcat/openwrt-packages#6]
mosdns已经更新v2.0.1版本，可以更新一下吗？

**Comment by dogbutcat** [comment]
I'm waiting for more "stable" one.

you can try docker version with latest version [github](https://github.com/dogbutcat/docker-mosdns) or [docker](https://hub.docker.com/r/dogbutcat/docker-mosdns)

**Comment by dudt** [comment]
> I'm waiting for more "stable" one.
> 
> you can try docker version with latest version [github](https://github.com/dogbutcat/docker-mosdns) or [docker](https://hub.docker.com/r/dogbutcat/docker-mosdns)

thx~
